exports.Section = {
	2: {
		"Slider"        : [],
		"SectionLayouts": [
			{
				"Name"        : "Программы",
				"Description" : "Из месяца в месяц мы подбираем для клиентов исключительные предложения по отелям, виллам, яхтам,  составляем увлекательные программы и маршруты. Мы предлагаем только то, что проверили сами. К Вашим услугам единственные в своем роде специалисты, которых мы привлекаем для организации  программ – активный отдых, образование за рубежом, свадебные путешествия, экскурсионные программы и многое другое.",
				"OfferLayouts": [
					{
						"Row"            : 0,
						"OfferLayoutType": "XL",
						"Offer1"         : {
							"Description"         : "Экскурсионные туры",
							"Id"                  : 48,
							"Url"                 : "/#/individualtours/category/22",
							"Name"                : "Экскурсионные туры",
							"Price"               : "",
							"Image"               : "https://s.inna.ru/Files/Photos/140313211940/140314174726/p_960x428.jpg",
							"ImageType"           : 2,
							"TypeName"            : "XL",
							"BackTitleRow1"       : "",
							"BackTitleRow2"       : "",
							"BackSubTitleRow1"    : "",
							"BackSubTitleRow2"    : "",
							"BackPrice"           : "",
							"FrontTitleRow1"      : "ЭКСКУРСИОННЫЕ ТУРЫ",
							"StyleFrontTitleRow1" : 1,
							"FrontTitleRow2"      : "",
							"StyleFrontTitleRow2" : 1,
							"FrontSubTitleRow1"   : "",
							"StyleFrontSubRow1"   : 1,
							"FrontSubTitleRow2"   : "",
							"StyleFrontSubRow2"   : 1,
							"FrontPrice"          : "",
							"StyleFrontPrice"     : 1,
							"OfferType"           : 1,
							"NeedFilterBrightness": true
						}
					},
					{
						"Row"            : 0,
						"OfferLayoutType": "2M",
						"Offer1"         : {
							"Description"         : "Свадебные туры",
							"Id"                  : 46,
							"Url"                 : "/#/individualtours/category/17",
							"Name"                : "Свадебные туры",
							"Price"               : "",
							"Image"               : "https://s.inna.ru/Files/Photos/140313211940/140314164709/p_475x320.jpg",
							"ImageType"           : 4,
							"TypeName"            : "M",
							"BackTitleRow1"       : "",
							"BackTitleRow2"       : "",
							"BackSubTitleRow1"    : "",
							"BackSubTitleRow2"    : "",
							"BackPrice"           : "",
							"FrontTitleRow1"      : "СВАДЬБЫ ЗА РУБЕЖОМ",
							"StyleFrontTitleRow1" : 1,
							"FrontTitleRow2"      : "",
							"StyleFrontTitleRow2" : 1,
							"FrontSubTitleRow1"   : "",
							"StyleFrontSubRow1"   : 1,
							"FrontSubTitleRow2"   : "",
							"StyleFrontSubRow2"   : 1,
							"FrontPrice"          : "",
							"StyleFrontPrice"     : 1,
							"OfferType"           : 1,
							"NeedFilterBrightness": true
						},
						"Offer2"         : {
							"Description"         : "Треккинг",
							"Id"                  : 50,
							"Url"                 : "/#/individualtours/category/12",
							"Name"                : "Треккинг",
							"Price"               : "",
							"Image"               : "https://s.inna.ru/Files/Photos/140211071125/140314175131/p_475x320.jpg",
							"ImageType"           : 4,
							"TypeName"            : "M",
							"BackTitleRow1"       : "",
							"BackTitleRow2"       : "",
							"BackSubTitleRow1"    : "",
							"BackSubTitleRow2"    : "",
							"BackPrice"           : "",
							"FrontTitleRow1"      : "ТРЕККИНГ",
							"StyleFrontTitleRow1" : 1,
							"FrontTitleRow2"      : "",
							"StyleFrontTitleRow2" : 1,
							"FrontSubTitleRow1"   : "",
							"StyleFrontSubRow1"   : 1,
							"FrontSubTitleRow2"   : "",
							"StyleFrontSubRow2"   : 1,
							"FrontPrice"          : "",
							"StyleFrontPrice"     : 1,
							"OfferType"           : 1,
							"NeedFilterBrightness": true
						}
					},
					{
						"Row"            : 0,
						"OfferLayoutType": "XL",
						"Offer1"         : {
							"Description"         : "Образование за рубежом",
							"Id"                  : 45,
							"Url"                 : "/#/individualtours/category/13",
							"Name"                : "Образование за рубежом",
							"Price"               : "",
							"Image"               : "https://s.inna.ru/Files/Photos/140225140208/140317182400/p_960x428.jpg",
							"ImageType"           : 2,
							"TypeName"            : "XL",
							"BackTitleRow1"       : "",
							"BackTitleRow2"       : "",
							"BackSubTitleRow1"    : "",
							"BackSubTitleRow2"    : "",
							"BackPrice"           : "",
							"FrontTitleRow1"      : "ОБРАЗОВАНИЕ ЗА РУБЕЖОМ",
							"StyleFrontTitleRow1" : 1,
							"FrontTitleRow2"      : "",
							"StyleFrontTitleRow2" : 1,
							"FrontSubTitleRow1"   : "",
							"StyleFrontSubRow1"   : 1,
							"FrontSubTitleRow2"   : "",
							"StyleFrontSubRow2"   : 1,
							"FrontPrice"          : "",
							"StyleFrontPrice"     : 1,
							"OfferType"           : 1,
							"NeedFilterBrightness": true
						}
					},
					{
						"Row"            : 0,
						"OfferLayoutType": "2M",
						"Offer1"         : {
							"Description"         : "Восхождения",
							"Id"                  : 47,
							"Url"                 : "/#/individualtours/category/24",
							"Name"                : "Восхождения",
							"Price"               : "",
							"Image"               : "https://s.inna.ru/Files/Photos/140313211940/140314171848/p_475x320.jpg",
							"ImageType"           : 4,
							"TypeName"            : "M",
							"BackTitleRow1"       : "",
							"BackTitleRow2"       : "",
							"BackSubTitleRow1"    : "",
							"BackSubTitleRow2"    : "",
							"BackPrice"           : "",
							"FrontTitleRow1"      : "ВОСХОЖДЕНИЯ",
							"StyleFrontTitleRow1" : 1,
							"FrontTitleRow2"      : "",
							"StyleFrontTitleRow2" : 1,
							"FrontSubTitleRow1"   : "",
							"StyleFrontSubRow1"   : 1,
							"FrontSubTitleRow2"   : "",
							"StyleFrontSubRow2"   : 1,
							"FrontPrice"          : "",
							"StyleFrontPrice"     : 1,
							"OfferType"           : 1,
							"NeedFilterBrightness": true
						},
						"Offer2"         : {
							"Description"         : "Полярные экспедиции",
							"Id"                  : 49,
							"Url"                 : "/#/individualtours/category/23",
							"Name"                : "Полярные экспедиции",
							"Price"               : "",
							"Image"               : "https://s.inna.ru/Files/Photos/140225140208/140314190111/p_475x320.jpg",
							"ImageType"           : 4,
							"TypeName"            : "M",
							"BackTitleRow1"       : "",
							"BackTitleRow2"       : "",
							"BackSubTitleRow1"    : "",
							"BackSubTitleRow2"    : "",
							"BackPrice"           : "",
							"FrontTitleRow1"      : "ПОЛЯРНЫЕ ЭКСПЕДИЦИИ",
							"StyleFrontTitleRow1" : 1,
							"FrontTitleRow2"      : "",
							"StyleFrontTitleRow2" : 1,
							"FrontSubTitleRow1"   : "",
							"StyleFrontSubRow1"   : 1,
							"FrontSubTitleRow2"   : "",
							"StyleFrontSubRow2"   : 1,
							"FrontPrice"          : "",
							"StyleFrontPrice"     : 1,
							"OfferType"           : 1,
							"NeedFilterBrightness": true
						}
					},
					{
						"Row"            : 0,
						"OfferLayoutType": "XL",
						"Offer1"         : {
							"Description"         : "Многие  из тех ,кто побывал в странах  Западной Европы,не откажутся еще раз увидеть страну  под   новым углом зрения  ,и  то что мы предлагаем может быть особенн¾  Ð·Ð°Ð¼Ð°Ð½ÑÐ¸Ð²Ð¾ Ð´Ð»Ñ ÑÐµÑ, ÐºÑÐ¾ Ð¸Ð½ÑÐµÑÐµÑÑÐµÑÑÑ Ð¸ÑÐºÑÑÑÑÐ²Ð¾Ð¼, Ð¼Ñ Ð½Ð°Ð´ÐµÐµÐ¼ÑÑ ÑÑÐ¾  Ð±ÑÐ´ÐµÑ Ð·Ð°Ð¼ÐµÑÐ°ÑÐµÐ»ÑÐ½Ð¾, ÐºÐ¾Ð³Ð´Ð° ÑÑÑÐ°Ð½Ñ Ð¿Ð¾ÐºÐ°Ð¶ÑÑ Ð½Ðµ Ð¿ÑÐ¾ÑÑÐ¾ ÑÐºÑÐºÑÑÑÐ¾Ð²Ð¾Ð´Ñ Ð°, Ð¿ÑÐµÐ´ÑÑÐ°Ð²Ð¸ÑÐµÐ»Ð¸ Ð¸ÑÐºÑÑÑÑÐ²Ð° Ñ Ð°ÑÑ-ÑÐµÑÐ°Ð¿ÐµÐ²ÑÐ¸ÑÐµÑÐºÐ¾Ð¹ Ð¿Ð¾Ð´Ð³Ð¾ÑÐ¾Ð²ÐºÐ¾Ð¹",
							"Id"                  : 92,
							"Url"                 : "/#/individualtours/category/40",
							"Name"                : "ÐÐ Ð¢ Ð¢Ð£Ð Ð«",
							"Price"               : "",
							"Image"               : "https://s.inna.ru/Files/Photos/140225140208/140430163416/p_960x428.jpg",
							"ImageType"           : 2,
							"TypeName"            : "XL",
							"BackTitleRow1"       : "",
							"BackTitleRow2"       : "",
							"BackSubTitleRow1"    : "",
							"BackSubTitleRow2"    : "",
							"BackPrice"           : "",
							"FrontTitleRow1"      : "ÐÐ Ð¢-Ð¢Ð£Ð Ð«",
							"StyleFrontTitleRow1" : 1,
							"FrontTitleRow2"      : "",
							"StyleFrontTitleRow2" : 1,
							"FrontSubTitleRow1"   : "",
							"StyleFrontSubRow1"   : 1,
							"FrontSubTitleRow2"   : "",
							"StyleFrontSubRow2"   : 1,
							"FrontPrice"          : "",
							"StyleFrontPrice"     : 1,
							"OfferType"           : 1,
							"NeedFilterBrightness": true
						}
					},
					{
						"Row"            : 0,
						"OfferLayoutType": "2M",
						"Offer1"         : {
							"Description"         : "",
							"Id"                  : 187,
							"Url"                 : "/#/individualtours/category/47",
							"Name"                : "ÐÐ·Ð´Ð¾ÑÐ¾Ð²Ð¸ÑÐµÐ»ÑÐ½ÑÐµ ÑÑÑÑ",
							"Price"               : "",
							"Image"               : "https://s.inna.ru/Files/Photos/140701164515/140807162434/p_475x320.jpg",
							"ImageType"           : 4,
							"TypeName"            : "M",
							"BackTitleRow1"       : "",
							"BackTitleRow2"       : "",
							"BackSubTitleRow1"    : "",
							"BackSubTitleRow2"    : "",
							"BackPrice"           : "",
							"FrontTitleRow1"      : "ÐÐÐÐÐ ÐÐÐÐ¢ÐÐÐ¬ÐÐ«Ð Ð¢Ð£Ð Ð«",
							"StyleFrontTitleRow1" : 1,
							"FrontTitleRow2"      : "",
							"StyleFrontTitleRow2" : 1,
							"FrontSubTitleRow1"   : "",
							"StyleFrontSubRow1"   : 1,
							"FrontSubTitleRow2"   : "",
							"StyleFrontSubRow2"   : 1,
							"FrontPrice"          : "",
							"StyleFrontPrice"     : 1,
							"OfferType"           : 1,
							"NeedFilterBrightness": true
						},
						"Offer2"         : {
							"Description"         : "",
							"Id"                  : 188,
							"Url"                 : "/#/individualtours/category/48",
							"Name"                : "ÐÐµÑÐµÐ½Ð¸Ðµ Ð·Ð° ÑÑÐ±ÐµÐ¶Ð¾Ð¼",
							"Price"               : "",
							"Image"               : "https://s.inna.ru/Files/Photos/140804135127/140807171240/p_475x320.jpg",
							"ImageType"           : 4,
							"TypeName"            : "M",
							"BackTitleRow1"       : "",
							"BackTitleRow2"       : "",
							"BackSubTitleRow1"    : "",
							"BackSubTitleRow2"    : "",
							"BackPrice"           : "",
							"FrontTitleRow1"      : "ÐÐÐ§ÐÐÐÐ ÐÐ Ð Ð£ÐÐÐÐÐ",
							"StyleFrontTitleRow1" : 1,
							"FrontTitleRow2"      : "",
							"StyleFrontTitleRow2" : 1,
							"FrontSubTitleRow1"   : "",
							"StyleFrontSubRow1"   : 1,
							"FrontSubTitleRow2"   : "",
							"StyleFrontSubRow2"   : 1,
							"FrontPrice"          : "",
							"StyleFrontPrice"     : 1,
							"OfferType"           : 1,
							"NeedFilterBrightness": true
						}
					}
				]
			}
		],
		"Landing"       : {"SectionTitle": "", "SubSectionTitle": "", "TextIntro": "", "RenderTextType": 1}
	},
	3: {
		"Slider"        : [
			{
				"Description"         : "",
				"Id"                  : 116,
				"Url"                 : "",
				"Name"                : "Общий по авиабилетам (заставка) ",
				"Price"               : "",
				"Image"               : "https://s.inna.ru/Files/Photos/140220133619/141028193948/p_O.jpg",
				"ImageType"           : 1,
				"TypeName"            : "XXL",
				"FrontTitleRow1"      : "",
				"StyleFrontTitleRow1" : 1,
				"FrontTitleRow2"      : "",
				"StyleFrontTitleRow2" : 0,
				"FrontSubTitleRow1"   : "",
				"StyleFrontSubRow1"   : 1,
				"FrontSubTitleRow2"   : "",
				"StyleFrontSubRow2"   : 0,
				"FrontPrice"          : "",
				"StyleFrontPrice"     : 0,
				"OfferType"           : 3,
				"NeedFilterBrightness": false
			}
		],
		"SectionLayouts": [
			{
				"Name"        : "АВИАБИЛЕТЫ",
				"Description" : "Отсутствие посредников, специальные тарифы  авиакомпаний, тарифы бюджетных \r\nавиаперевозчиков позволили сформировать уникальный ассортимент предложений и обеспечить низкие цены. Теперь Вам не нужно \r\nискать билеты на множестве сайтов.",
				"OfferLayouts": [
					{
						"Row"            : 0,
						"OfferLayoutType": "XL",
						"Offer1"         : {
							"Description"         : "",
							"Id"                  : 117,
							"Url"                 : "http://www.rusline.aero",
							"Name"                : "Руслайн",
							"Price"               : "",
							"Image"               : "https://s.inna.ru/Files/Photos/140602102203/140624122237/p_960x428.jpg",
							"ImageType"           : 2,
							"TypeName"            : "XL",
							"BackTitleRow1"       : "",
							"BackTitleRow2"       : "",
							"BackSubTitleRow1"    : "",
							"BackSubTitleRow2"    : "",
							"BackPrice"           : "",
							"FrontTitleRow1"      : "",
							"StyleFrontTitleRow1" : 1,
							"FrontTitleRow2"      : "",
							"StyleFrontTitleRow2" : 1,
							"FrontSubTitleRow1"   : "",
							"StyleFrontSubRow1"   : 1,
							"FrontSubTitleRow2"   : "",
							"StyleFrontSubRow2"   : 1,
							"FrontPrice"          : "",
							"StyleFrontPrice"     : 1,
							"OfferType"           : 3,
							"NeedFilterBrightness": false
						}
					}
				]
			}
		],
		"Landing"       : {"SectionTitle": "", "SubSectionTitle": "", "TextIntro": "", "RenderTextType": 1}
	},
	4: {
		"Slider"        : [
			{
				"Description"         : "",
				"Id"                  : 118,
				"Url"                 : "",
				"Name"                : "Общий по ДП (заставка)",
				"Price"               : "",
				"Image"               : "https://s.inna.ru/Files/Photos/140220092948/141028191927/p_O.jpg",
				"ImageType"           : 1,
				"TypeName"            : "XXL",
				"FrontTitleRow1"      : "",
				"StyleFrontTitleRow1" : 1,
				"FrontTitleRow2"      : "",
				"StyleFrontTitleRow2" : 1,
				"FrontSubTitleRow1"   : "",
				"StyleFrontSubRow1"   : 1,
				"FrontSubTitleRow2"   : "",
				"StyleFrontSubRow2"   : 1,
				"FrontPrice"          : "",
				"StyleFrontPrice"     : 1,
				"OfferType"           : 5,
				"NeedFilterBrightness": false
			}
		],
		"SectionLayouts": [
			{
				"Name"        : "Лучшие предложения",
				"Description" : "Динамический турпакет (перелет+отель) это возможность получить экономию до 20% за счет специальных пакетных тарифов от наших поставщиков. Мы предлагаем более 200 стран мира с моментальным подтверждением и оплатой на сайте банковской картой. Сразу после оплаты мы направим на вашу электронную почту билет на регулярный рейс и ваучер отеля. ",
				"OfferLayouts": [
					{
						"Row"            : 0,
						"OfferLayoutType": "XL",
						"Offer1"         : {
							"Description"         : "",
							"Id"                  : 394,
							"Url"                 : "/#/packages/search/6733-97304-12.04.2015-19.04.2015-0-2-",
							"Name"                : "Мальдивы",
							"Price"               : "",
							"Image"               : "https://s.inna.ru/Files/Photos/140219135744/150312114727/p_960x428.jpg",
							"ImageType"           : 2,
							"TypeName"            : "XL",
							"BackTitleRow1"       : "МАЛЬДИВЫ",
							"BackTitleRow2"       : "12-19 апреля, 7 ночей",
							"BackSubTitleRow1"    : "",
							"BackSubTitleRow2"    : "Перелет + Отель",
							"BackPrice"           : "37 486 руб (за чел.)",
							"FrontTitleRow1"      : "МАЛЬДИВЫ",
							"StyleFrontTitleRow1" : 1,
							"FrontTitleRow2"      : "",
							"StyleFrontTitleRow2" : 1,
							"FrontSubTitleRow1"   : "12-19 апреля, 7 ночей",
							"StyleFrontSubRow1"   : 1,
							"FrontSubTitleRow2"   : "",
							"StyleFrontSubRow2"   : 1,
							"FrontPrice"          : "37 486 руб (за чел.)",
							"StyleFrontPrice"     : 1,
							"OfferType"           : 5,
							"NeedFilterBrightness": true
						}
					},
					{
						"Row"            : 0,
						"OfferLayoutType": "L2S",
						"Offer1"         : {
							"Description"         : "",
							"Id"                  : 376,
							"Url"                 : "/#/packages/search/6733-2397-18.04.2015-25.04.2015-0-2-",
							"Name"                : "Хургада",
							"Price"               : "",
							"Image"               : "https://s.inna.ru/Files/Photos/140211071125/150312114619/p_637x428.jpg",
							"ImageType"           : 3,
							"TypeName"            : "L",
							"BackTitleRow1"       : "ХУРГАДА",
							"BackTitleRow2"       : "18-25 апреля, 7 ночей",
							"BackSubTitleRow1"    : "",
							"BackSubTitleRow2"    : "Перелет + Отель",
							"BackPrice"           : "30 368 руб (за чел.)",
							"FrontTitleRow1"      : "ХУРГАДА",
							"StyleFrontTitleRow1" : 1,
							"FrontTitleRow2"      : "",
							"StyleFrontTitleRow2" : 1,
							"FrontSubTitleRow1"   : "18-25 апреля, 7 ночей",
							"StyleFrontSubRow1"   : 1,
							"FrontSubTitleRow2"   : "",
							"StyleFrontSubRow2"   : 1,
							"FrontPrice"          : "30 368 руб (за чел.)",
							"StyleFrontPrice"     : 1,
							"OfferType"           : 5,
							"NeedFilterBrightness": true
						},
						"Offer2"         : {
							"Description"         : "",
							"Id"                  : 377,
							"Url"                 : "/#/packages/search/6733-1319-10.04.2015-19.04.2015-0-2-",
							"Name"                : "Маврикий",
							"Price"               : "",
							"Image"               : "https://s.inna.ru/Files/Photos/140211071106/150312114521/p_313x209.jpg",
							"ImageType"           : 5,
							"TypeName"            : "S",
							"BackTitleRow1"       : "МАВРИКИЙ",
							"BackTitleRow2"       : "10-19 апреля, 9 ночей",
							"BackSubTitleRow1"    : "",
							"BackSubTitleRow2"    : "Перелет + Отель",
							"BackPrice"           : "72 328 руб (за чел.)",
							"FrontTitleRow1"      : "МАВРИКИЙ",
							"StyleFrontTitleRow1" : 1,
							"FrontTitleRow2"      : "",
							"StyleFrontTitleRow2" : 1,
							"FrontSubTitleRow1"   : "10-19 апреля, 9 ночей",
							"StyleFrontSubRow1"   : 1,
							"FrontSubTitleRow2"   : "",
							"StyleFrontSubRow2"   : 1,
							"FrontPrice"          : "72 328 руб (за чел.)",
							"StyleFrontPrice"     : 1,
							"OfferType"           : 5,
							"NeedFilterBrightness": true
						},
						"Offer3"         : {
							"Description"         : "",
							"Id"                  : 378,
							"Url"                 : "/#/packages/search/6733-97301-04.04.2015-14.04.2015-0-2-",
							"Name"                : "Сейшелы",
							"Price"               : "",
							"Image"               : "https://s.inna.ru/Files/Photos/140211071105/150312114419/p_313x209.jpg",
							"ImageType"           : 5,
							"TypeName"            : "S",
							"BackTitleRow1"       : "СЕЙШЕЛЫ",
							"BackTitleRow2"       : "4-14 апреля, 10 ночей",
							"BackSubTitleRow1"    : "",
							"BackSubTitleRow2"    : "Перелет + Отель",
							"BackPrice"           : "66 641 руб (за чел.)",
							"FrontTitleRow1"      : "СЕЙШЕЛЫ",
							"StyleFrontTitleRow1" : 1,
							"FrontTitleRow2"      : "",
							"StyleFrontTitleRow2" : 1,
							"FrontSubTitleRow1"   : "4-14 апреля, 10 ночей",
							"StyleFrontSubRow1"   : 1,
							"FrontSubTitleRow2"   : "",
							"StyleFrontSubRow2"   : 1,
							"FrontPrice"          : "66 641 руб (за чел.)",
							"StyleFrontPrice"     : 1,
							"OfferType"           : 5,
							"NeedFilterBrightness": true
						}
					},
					{
						"Row"            : 0,
						"OfferLayoutType": "2SL",
						"Offer1"         : {
							"Description"         : "",
							"Id"                  : 379,
							"Url"                 : "/#/packages/search/6733-1735-08.04.2015-12.04.2015-0-2-",
							"Name"                : "Париж",
							"Price"               : "",
							"Image"               : "https://s.inna.ru/Files/Photos/150312114321/150312114321/p_313x209.jpg",
							"ImageType"           : 5,
							"TypeName"            : "S",
							"BackTitleRow1"       : "ПАРИЖ",
							"BackTitleRow2"       : "8-12 апреля, 4 ночи",
							"BackSubTitleRow1"    : "",
							"BackSubTitleRow2"    : "Перелет + Отель",
							"BackPrice"           : "24 653 руб (за чел.)",
							"FrontTitleRow1"      : "ПАРИЖ",
							"StyleFrontTitleRow1" : 1,
							"FrontTitleRow2"      : "",
							"StyleFrontTitleRow2" : 1,
							"FrontSubTitleRow1"   : "8-12 апреля, 4 ночи",
							"StyleFrontSubRow1"   : 1,
							"FrontSubTitleRow2"   : "",
							"StyleFrontSubRow2"   : 1,
							"FrontPrice"          : "24 653 руб (за чел.)",
							"StyleFrontPrice"     : 1,
							"OfferType"           : 5,
							"NeedFilterBrightness": true
						},
						"Offer2"         : {
							"Description"         : "",
							"Id"                  : 380,
							"Url"                 : "/#/packages/search/6733-673-14.04.2015-21.04.2015-0-2-",
							"Name"                : "Пекин",
							"Price"               : "",
							"Image"               : "https://s.inna.ru/Files/Photos/141204150356/150312114227/p_313x209.jpg",
							"ImageType"           : 5,
							"TypeName"            : "S",
							"BackTitleRow1"       : "ПЕКИН",
							"BackTitleRow2"       : "14-21 апреля, 7 ночей",
							"BackSubTitleRow1"    : "",
							"BackSubTitleRow2"    : "Перелет + Отель",
							"BackPrice"           : "26 678 руб (за чел.)",
							"FrontTitleRow1"      : "ПЕКИН",
							"StyleFrontTitleRow1" : 1,
							"FrontTitleRow2"      : "",
							"StyleFrontTitleRow2" : 1,
							"FrontSubTitleRow1"   : "14-21 апреля, 7 ночей",
							"StyleFrontSubRow1"   : 1,
							"FrontSubTitleRow2"   : "",
							"StyleFrontSubRow2"   : 1,
							"FrontPrice"          : "26 678 руб (за чел.)",
							"StyleFrontPrice"     : 1,
							"OfferType"           : 5,
							"NeedFilterBrightness": true
						},
						"Offer3"         : {
							"Description"         : "",
							"Id"                  : 381,
							"Url"                 : "/#/packages/search/6733-3443-04.04.2015-14.04.2015-0-2-",
							"Name"                : "Фантьет-Муйне",
							"Price"               : "",
							"Image"               : "https://s.inna.ru/Files/Photos/141204150356/150312114125/p_637x428.jpg",
							"ImageType"           : 3,
							"TypeName"            : "L",
							"BackTitleRow1"       : "ФАНТЬЕТ-МУЙНЕ",
							"BackTitleRow2"       : "4-14 апреля, 10 ночей",
							"BackSubTitleRow1"    : "",
							"BackSubTitleRow2"    : "Перелет + Отель",
							"BackPrice"           : "35 989 руб (за чел.)",
							"FrontTitleRow1"      : "ФАНТЬЕТ-МУЙНЕ",
							"StyleFrontTitleRow1" : 1,
							"FrontTitleRow2"      : "",
							"StyleFrontTitleRow2" : 1,
							"FrontSubTitleRow1"   : "4-14 апреля, 10 ночей",
							"StyleFrontSubRow1"   : 1,
							"FrontSubTitleRow2"   : "",
							"StyleFrontSubRow2"   : 1,
							"FrontPrice"          : "35 989 руб (за чел.)",
							"StyleFrontPrice"     : 1,
							"OfferType"           : 5,
							"NeedFilterBrightness": true
						}
					},
					{
						"Row"            : 0,
						"OfferLayoutType": "XL",
						"Offer1"         : {
							"Description"         : "",
							"Id"                  : 395,
							"Url"                 : "/#/packages/search/6733-54608-11.04.2015-21.04.2015-0-2-",
							"Name"                : "Бали",
							"Price"               : "",
							"Image"               : "https://s.inna.ru/Files/Photos/141204150356/150312114028/p_960x428.jpg",
							"ImageType"           : 2,
							"TypeName"            : "XL",
							"BackTitleRow1"       : "БАЛИ",
							"BackTitleRow2"       : "11-21 апреля, 10 ночей",
							"BackSubTitleRow1"    : "",
							"BackSubTitleRow2"    : "Перелет + Отель",
							"BackPrice"           : "52 455 руб (за чел.)",
							"FrontTitleRow1"      : "БАЛИ",
							"StyleFrontTitleRow1" : 1,
							"FrontTitleRow2"      : "",
							"StyleFrontTitleRow2" : 1,
							"FrontSubTitleRow1"   : "11-21 апреля, 10 ночей",
							"StyleFrontSubRow1"   : 1,
							"FrontSubTitleRow2"   : "",
							"StyleFrontSubRow2"   : 1,
							"FrontPrice"          : "52 455 руб (за чел.)",
							"StyleFrontPrice"     : 1,
							"OfferType"           : 5,
							"NeedFilterBrightness": true
						}
					},
					{
						"Row"            : 0,
						"OfferLayoutType": "2M",
						"Offer1"         : {
							"Description"         : "",
							"Id"                  : 382,
							"Url"                 : "/#/packages/search/6733-4527-03.04.2015-08.04.2015-0-2-",
							"Name"                : "Тель-Авив",
							"Price"               : "",
							"Image"               : "https://s.inna.ru/Files/Photos/141204150356/150312113934/p_475x320.jpg",
							"ImageType"           : 4,
							"TypeName"            : "M",
							"BackTitleRow1"       : "ТЕЛЬ-АВИВ",
							"BackTitleRow2"       : "3-8 апреля, 5 ночей",
							"BackSubTitleRow1"    : "",
							"BackSubTitleRow2"    : "Перелет + Отель",
							"BackPrice"           : "19 778 руб (за чел.)",
							"FrontTitleRow1"      : "ТЕЛЬ-АВИВ",
							"StyleFrontTitleRow1" : 1,
							"FrontTitleRow2"      : "",
							"StyleFrontTitleRow2" : 1,
							"FrontSubTitleRow1"   : "3-8 апреля, 5 ночей",
							"StyleFrontSubRow1"   : 1,
							"FrontSubTitleRow2"   : "",
							"StyleFrontSubRow2"   : 1,
							"FrontPrice"          : "19 778 руб (за чел.)",
							"StyleFrontPrice"     : 1,
							"OfferType"           : 5,
							"NeedFilterBrightness": true
						},
						"Offer2"         : {
							"Description"         : "",
							"Id"                  : 383,
							"Url"                 : "/#/packages/search/6733-563-15.04.2015-19.04.2015-0-2-",
							"Name"                : "Барселона",
							"Price"               : "",
							"Image"               : "https://s.inna.ru/Files/Photos/141204150356/150312113833/p_475x320.jpg",
							"ImageType"           : 4,
							"TypeName"            : "M",
							"BackTitleRow1"       : "БАРСЕЛОНА",
							"BackTitleRow2"       : "15-19 апреля, 4 ночи",
							"BackSubTitleRow1"    : "",
							"BackSubTitleRow2"    : "Перелет + Отель",
							"BackPrice"           : "23 341 руб (за чел.)",
							"FrontTitleRow1"      : "БАРСЕЛОНА",
							"StyleFrontTitleRow1" : 1,
							"FrontTitleRow2"      : "",
							"StyleFrontTitleRow2" : 1,
							"FrontSubTitleRow1"   : "15-19 апреля, 4 ночи",
							"StyleFrontSubRow1"   : 1,
							"FrontSubTitleRow2"   : "",
							"StyleFrontSubRow2"   : 1,
							"FrontPrice"          : "23 341 руб (за чел.)",
							"StyleFrontPrice"     : 1,
							"OfferType"           : 5,
							"NeedFilterBrightness": true
						}
					},
					{
						"Row"            : 0,
						"OfferLayoutType": "XL",
						"Offer1"         : {
							"Description"         : "",
							"Id"                  : 384,
							"Url"                 : "/#/packages/search/6733-5954-02.04.2015-05.04.2015-0-2-",
							"Name"                : "Прага",
							"Price"               : "",
							"Image"               : "https://s.inna.ru/Files/Photos/141204150356/150312113732/p_960x428.jpg",
							"ImageType"           : 2,
							"TypeName"            : "XL",
							"BackTitleRow1"       : "ПРАГА",
							"BackTitleRow2"       : "2-5 апреля, 3 ночи",
							"BackSubTitleRow1"    : "",
							"BackSubTitleRow2"    : "Перелет + Отель",
							"BackPrice"           : "19 537 руб (за чел.)",
							"FrontTitleRow1"      : "ПРАГА",
							"StyleFrontTitleRow1" : 1,
							"FrontTitleRow2"      : "",
							"StyleFrontTitleRow2" : 1,
							"FrontSubTitleRow1"   : "2-5 апреля, 3 ночи",
							"StyleFrontSubRow1"   : 1,
							"FrontSubTitleRow2"   : "",
							"StyleFrontSubRow2"   : 1,
							"FrontPrice"          : "19 537 руб (за чел.)",
							"StyleFrontPrice"     : 1,
							"OfferType"           : 5,
							"NeedFilterBrightness": true
						}
					},
					{
						"Row"            : 0,
						"OfferLayoutType": "L2S",
						"Offer1"         : {
							"Description"         : "",
							"Id"                  : 385,
							"Url"                 : "/#/packages/search/6733-6709-04.04.2015-09.04.2015-0-2-",
							"Name"                : "Стамбул",
							"Price"               : "",
							"Image"               : "https://s.inna.ru/Files/Photos/141204150356/150312113625/p_637x428.jpg",
							"ImageType"           : 3,
							"TypeName"            : "L",
							"BackTitleRow1"       : "СТАМБУЛ",
							"BackTitleRow2"       : "4-9 апреля, 5 ночей",
							"BackSubTitleRow1"    : "",
							"BackSubTitleRow2"    : "Перелет + Отель",
							"BackPrice"           : "20 290 руб (за чел.)",
							"FrontTitleRow1"      : "СТАМБУЛ",
							"StyleFrontTitleRow1" : 1,
							"FrontTitleRow2"      : "",
							"StyleFrontTitleRow2" : 1,
							"FrontSubTitleRow1"   : "4-9 апреля, 5 ночей",
							"StyleFrontSubRow1"   : 1,
							"FrontSubTitleRow2"   : "",
							"StyleFrontSubRow2"   : 1,
							"FrontPrice"          : "20 290 руб (за чел.)",
							"StyleFrontPrice"     : 1,
							"OfferType"           : 5,
							"NeedFilterBrightness": true
						},
						"Offer2"         : {
							"Description"         : "",
							"Id"                  : 386,
							"Url"                 : "/#/packages/search/6733-45602-09.05.2015-16.05.2015-0-2-",
							"Name"                : "Крит",
							"Price"               : "",
							"Image"               : "https://s.inna.ru/Files/Photos/141204150356/150312113502/p_313x209.jpg",
							"ImageType"           : 5,
							"TypeName"            : "S",
							"BackTitleRow1"       : "КРИТ",
							"BackTitleRow2"       : "9-16 мая, 7 ночей",
							"BackSubTitleRow1"    : "",
							"BackSubTitleRow2"    : "Перелет + Отель",
							"BackPrice"           : "25 757 руб (за чел.)",
							"FrontTitleRow1"      : "КРИТ",
							"StyleFrontTitleRow1" : 1,
							"FrontTitleRow2"      : "",
							"StyleFrontTitleRow2" : 1,
							"FrontSubTitleRow1"   : "9-16 мая, 7 ночей",
							"StyleFrontSubRow1"   : 1,
							"FrontSubTitleRow2"   : "",
							"StyleFrontSubRow2"   : 1,
							"FrontPrice"          : "25 757 руб (за чел.)",
							"StyleFrontPrice"     : 1,
							"OfferType"           : 5,
							"NeedFilterBrightness": true
						},
						"Offer3"         : {
							"Description"         : "",
							"Id"                  : 387,
							"Url"                 : "/#/packages/search/6733-49210-16.05.2015-23.05.2015-0-2-",
							"Name"                : "Халкидики",
							"Price"               : "",
							"Image"               : "https://s.inna.ru/Files/Photos/141204150356/150312113314/p_313x209.jpg",
							"ImageType"           : 5,
							"TypeName"            : "S",
							"BackTitleRow1"       : "ХАЛКИДИКИ",
							"BackTitleRow2"       : "16-23 мая, 7 ночей",
							"BackSubTitleRow1"    : "",
							"BackSubTitleRow2"    : "Перелет + Отель",
							"BackPrice"           : "19 509 руб (за чел.)",
							"FrontTitleRow1"      : "ХАЛКИДИКИ",
							"StyleFrontTitleRow1" : 1,
							"FrontTitleRow2"      : "",
							"StyleFrontTitleRow2" : 1,
							"FrontSubTitleRow1"   : "16-23 мая, 7 ночей",
							"StyleFrontSubRow1"   : 1,
							"FrontSubTitleRow2"   : "",
							"StyleFrontSubRow2"   : 1,
							"FrontPrice"          : "19 509 руб (за чел.)",
							"StyleFrontPrice"     : 1,
							"OfferType"           : 5,
							"NeedFilterBrightness": true
						}
					},
					{
						"Row"            : 0,
						"OfferLayoutType": "L3L3L3",
						"Offer1"         : {
							"Description"         : "",
							"Id"                  : 388,
							"Url"                 : "/#/packages/search/6733-741-23.05.2015-30.05.2015-0-2-",
							"Name"                : "Созополь",
							"Price"               : "",
							"Image"               : "https://s.inna.ru/Files/Photos/141204150356/150312112904/p_313x209.jpg",
							"ImageType"           : 7,
							"TypeName"            : "L3",
							"BackTitleRow1"       : "СОЗОПОЛЬ",
							"BackTitleRow2"       : "23-30 мая, 7 ночей",
							"BackSubTitleRow1"    : "",
							"BackSubTitleRow2"    : "Перелет + Отель",
							"BackPrice"           : "26 453 руб (за чел.)",
							"FrontTitleRow1"      : "СОЗОПОЛЬ",
							"StyleFrontTitleRow1" : 1,
							"FrontTitleRow2"      : "",
							"StyleFrontTitleRow2" : 1,
							"FrontSubTitleRow1"   : "23-30 мая, 7 ночей",
							"StyleFrontSubRow1"   : 1,
							"FrontSubTitleRow2"   : "",
							"StyleFrontSubRow2"   : 1,
							"FrontPrice"          : "26 453 руб (за чел.)",
							"StyleFrontPrice"     : 1,
							"OfferType"           : 5,
							"NeedFilterBrightness": true
						},
						"Offer2"         : {
							"Description"         : "",
							"Id"                  : 389,
							"Url"                 : "/#/packages/search/6733-59429-10.05.2015-17.05.2015-0-2-",
							"Name"                : "Кемер",
							"Price"               : "",
							"Image"               : "https://s.inna.ru/Files/Photos/141204150356/150312112738/p_313x209.jpg",
							"ImageType"           : 7,
							"TypeName"            : "L3",
							"BackTitleRow1"       : "КЕМЕР",
							"BackTitleRow2"       : "10-17 мая, 7 ночей",
							"BackSubTitleRow1"    : "",
							"BackSubTitleRow2"    : "Перелет + Отель",
							"BackPrice"           : "30 395 руб (за чел.)",
							"FrontTitleRow1"      : "КЕМЕР",
							"StyleFrontTitleRow1" : 1,
							"FrontTitleRow2"      : "",
							"StyleFrontTitleRow2" : 1,
							"FrontSubTitleRow1"   : "10-17 мая, 7 ночей",
							"StyleFrontSubRow1"   : 1,
							"FrontSubTitleRow2"   : "",
							"StyleFrontSubRow2"   : 1,
							"FrontPrice"          : "30 395 руб (за чел.)",
							"StyleFrontPrice"     : 1,
							"OfferType"           : 5,
							"NeedFilterBrightness": true
						},
						"Offer3"         : {
							"Description"         : "",
							"Id"                  : 390,
							"Url"                 : "/#/packages/search/6733-18820-03.06.2015-10.06.2015-0-2-",
							"Name"                : "Сочи",
							"Price"               : "",
							"Image"               : "https://s.inna.ru/Files/Photos/141204150356/150312112633/p_313x209.jpg",
							"ImageType"           : 7,
							"TypeName"            : "L3",
							"BackTitleRow1"       : "СОЧИ",
							"BackTitleRow2"       : "3-10 июня, 7 ночей",
							"BackSubTitleRow1"    : "",
							"BackSubTitleRow2"    : "Перелет + Отель",
							"BackPrice"           : "18 104 руб (за чел.)",
							"FrontTitleRow1"      : "СОЧИ",
							"StyleFrontTitleRow1" : 1,
							"FrontTitleRow2"      : "",
							"StyleFrontTitleRow2" : 1,
							"FrontSubTitleRow1"   : "3-10 июня, 7 ночей",
							"StyleFrontSubRow1"   : 1,
							"FrontSubTitleRow2"   : "",
							"StyleFrontSubRow2"   : 1,
							"FrontPrice"          : "18 104 руб (за чел.)",
							"StyleFrontPrice"     : 1,
							"OfferType"           : 5,
							"NeedFilterBrightness": true
						}
					},
					{
						"Row"            : 0,
						"OfferLayoutType": "XL",
						"Offer1"         : {
							"Description"         : "",
							"Id"                  : 391,
							"Url"                 : "/#/packages/search/6733-3053-11.04.2015-18.04.2015-0-2-",
							"Name"                : "Лиссабон",
							"Price"               : "",
							"Image"               : "https://s.inna.ru/Files/Photos/141204150356/150312112536/p_960x428.jpg",
							"ImageType"           : 2,
							"TypeName"            : "XL",
							"BackTitleRow1"       : "ЛИССАБОН",
							"BackTitleRow2"       : "11-18 апреля, 7 ночей",
							"BackSubTitleRow1"    : "",
							"BackSubTitleRow2"    : "Перелет + Отель",
							"BackPrice"           : "24 156 руб (за чел.)",
							"FrontTitleRow1"      : "ЛИССАБОН",
							"StyleFrontTitleRow1" : 1,
							"FrontTitleRow2"      : "",
							"StyleFrontTitleRow2" : 1,
							"FrontSubTitleRow1"   : "11-18 апреля, 7 ночей",
							"StyleFrontSubRow1"   : 1,
							"FrontSubTitleRow2"   : "",
							"StyleFrontSubRow2"   : 1,
							"FrontPrice"          : "24 156 руб (за чел.)",
							"StyleFrontPrice"     : 1,
							"OfferType"           : 5,
							"NeedFilterBrightness": true
						}
					},
					{
						"Row"            : 0,
						"OfferLayoutType": "2M",
						"Offer1"         : {
							"Description"         : "",
							"Id"                  : 392,
							"Url"                 : "/#/packages/search/6733-4756-15.04.2015-19.04.2015-0-2-",
							"Name"                : "Венеция",
							"Price"               : "",
							"Image"               : "https://s.inna.ru/Files/Photos/141204150356/150312112425/p_475x320.jpg",
							"ImageType"           : 4,
							"TypeName"            : "M",
							"BackTitleRow1"       : "ВЕНЕЦИЯ",
							"BackTitleRow2"       : "15-19 апреля, 4 ночи",
							"BackSubTitleRow1"    : "",
							"BackSubTitleRow2"    : "Перелет + Отель",
							"BackPrice"           : "25 744 руб (за чел.)",
							"FrontTitleRow1"      : "ВЕНЕЦИЯ",
							"StyleFrontTitleRow1" : 1,
							"FrontTitleRow2"      : "",
							"StyleFrontTitleRow2" : 1,
							"FrontSubTitleRow1"   : "15-19 апреля, 4 ночи",
							"StyleFrontSubRow1"   : 1,
							"FrontSubTitleRow2"   : "",
							"StyleFrontSubRow2"   : 1,
							"FrontPrice"          : "25 744 руб (за чел.)",
							"StyleFrontPrice"     : 1,
							"OfferType"           : 5,
							"NeedFilterBrightness": true
						},
						"Offer2"         : {
							"Description"         : "",
							"Id"                  : 393,
							"Url"                 : "/#/packages/search/6733-4643-09.05.2015-16.05.2015-0-2-",
							"Name"                : "Токио",
							"Price"               : "",
							"Image"               : "https://s.inna.ru/Files/Photos/141204150356/150312112326/p_475x320.jpg",
							"ImageType"           : 4,
							"TypeName"            : "M",
							"BackTitleRow1"       : "ТОКИО",
							"BackTitleRow2"       : "9-16 мая, 7 ночей",
							"BackSubTitleRow1"    : "",
							"BackSubTitleRow2"    : "Перелет + Отель",
							"BackPrice"           : "41 551 руб (за чел.)",
							"FrontTitleRow1"      : "ТОКИО",
							"StyleFrontTitleRow1" : 1,
							"FrontTitleRow2"      : "",
							"StyleFrontTitleRow2" : 1,
							"FrontSubTitleRow1"   : "9-16 мая, 7 ночей",
							"StyleFrontSubRow1"   : 1,
							"FrontSubTitleRow2"   : "",
							"StyleFrontSubRow2"   : 1,
							"FrontPrice"          : "41 551 руб (за чел.)",
							"StyleFrontPrice"     : 1,
							"OfferType"           : 5,
							"NeedFilterBrightness": true
						}
					}
				]
			}
		],
		"Landing"       : {"SectionTitle": "", "SubSectionTitle": "", "TextIntro": "", "RenderTextType": 1}
	}
}